/*Inserting into Establishment, Be sure to remember which entires into table, since the ID autoincrements
Also: when it comes to establishments which are multiple categories: Just give it the main one: IE: Lyberry is a Bar, Yates is a Restaurant*/
/*1*/insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Las Iguanas", "108-111 East Side Plaza, Gunwharf Quays", "Portsmouth", "PO1 3SY", "Flame grilled Latin American food and sharing dishes", 'Restaurant');
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Restaurant 27", "27A South Parade, Southsea", "Portsmouth", "PO5 2JF", "Upper class French cuisine", "Restaurant");
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Pie and Vinyl", "59-61 Castle Road, Southsea", "Portsmouth", "PO5 3AY", "Unique pie and mash restaurant connected to a record shop. Serves locally sourced pies as well as vegan and gluten free", "Restaurant");
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("The Kitchen", "Florence Road", "Portsmouth", "PO5 2NA", "High end cuisine with unique takes on British dishes with international influences", "Restaurant");
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Samphire", "1 Kent Road", "Portsmouth", "PO5 3EG", "Classy seafood restaurant that also sells British cuisine including Roast Dinners and Fish & Chips", "Restaurant");
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Montparnasse", "103 Palmerston Road", "Portsmouth", "PO5 3PS", "French inspired, high end restaurant commonly known for beautiful looking dishes", "Restaurant");
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Becketts Southsea", "11 Bellevue Terrace, Southsea", "Portsmouth", "PO5 3AT", "Cosy and comforting British restaurant", "Restaurant");
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("The Wave Maiden", "36 Osborne Road", "Portsmouth", "PO5 3LT", "A mash up of British and American cuisine that often has live music and great atmosphere", "Restaurant");
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Brasserie Blanc", "1 Gunwharf Quays", "Portsmouth", "PO1 3FR", "Known for seafood dishes known for French inspired menu", "Restaurant");
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Abarbistro", "58 White Road", "Portsmouth", "PO1 2JA", "Beautifully presented dishes with a variety of cuisines", "Restaurant");
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("The Chambers", "27 Landport Terrace", "Portsmouth" , "PO1 2RG", "Lounge and Restaurant housed in a cosy building with unique decor", "Restaurant");
/*12*/insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Haldi", "93 Albert Road", "Portsmouth", "PO5 2SG", "Traditional Indian Restaurant", 'Restaurant');
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Spice Merchants", "44 Osborne Road", "Portsmouth", "PO5 3LT", "Unpretentious curry house cooking Indian staples and creative modern dishes with seafood options." , 'Restaurant');
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Purple Mango", "27 Albet Road", "Portsmouth", "PO5 2SE", "Classic curry house for eat in or take away", 'Restaurant');
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("T & J Mahal", "39 Elm Grove", "Portsmouth", "PO5 1JF", "Popular Indian restaurant with a modern interior", 'Restaurant');
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Massala Room", "245 London Road", "Portsmouth", "PO2 9HA", "Friendly and welcoming Indian restaurant", 'Restaurant');
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("The Gandhi Restaurant", "139-141 Kingston Road", "Portsmouth", "PO2 7EB", "Indian regional staples in a swish curry house with coloured lighting, white booths and banquettes.", 'Restaurant');
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Spice Route Indian Cusine", "101 Palmerston Road", "Portsmouth", "PO5 3PS", "Popular among locals for traditional curries", 'Restaurant');
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Kadir's Indian Street Food", "217 Alber Road", "Portsmouth", "PO4 0JP", "A modern take on curries with a street food vibe", 'Restaurant');
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Kassia, Southsea", "82 Osborne Road", "Portsmouth", "PO5 3LU", "Known for it's unique Indian tapas experience", 'Restaurant');
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("The Akash", "99 Albert Road", "Portsmouth", "PO5 2SG", "Popular, family-run balti house dating back to the 1970s, serving classic Indian dishes.", 'Restaurant');
/*22*/insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Tin Tin", "28 The Hard", "Portsmouth", "PO1 3DT", "Chinese Restaurant and Takeaway", "Restaurant");
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Noble House Chinese", "43 Osborne Road", "Portsmouth", "PO5 3LT", "Chinese restraunt with Cantonese specialities", "Restaurant");
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Real China", "7 Albert Road", "Portsmouth", "PO5 2SE", "Classic chinese restraunt", "Restaurant");
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Wok and Chips", "129 Winter Road", "Portsmouth", "PO4 8DS", "Casual chinese restraunt", "Restaurant");
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Kam Too", "44 St. Marys Road", "Portsmouth", "PO1 5PH", "Chinese restaurant with a huge variety of dishes", "Restaurant");
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Golden Bowl", "71 Fawcett Road", "Portsmouth", "PO4 0DB", "Fun and quirky Chinese restaurant", "Restaurant");
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Mayfair", "96 Castle Road", "Portsmouth", "PO5 3AZ", "Popular chinese restaurant and takeaway, particularly with chinese nationals", "Restaurant");
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Yan Woo", "33 Kingston Road", "Portsmouth", "PO2 7DP", "Great chinese restaurant for groups", "Restaurant");
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("The Mary Rose & Dragon", "19 St Georges Road", "Portsmouth", "PO1 2EW", "Unique chinese restaurant located in an old pub", "Restaurant");
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Spicy House", "8 Grove Road South", "Portsmouth", "PO5 3QT", "Popular chinese takeaway but has a small space for eating in", "Restaurant");
/*32*/insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Soprano's", "108 Palmerston Road", "Portsmouth", "PO5 2PT", "", 'Restaurant');
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Don Claudio Italian Restaurant", "15 Jubilee Terrance", "Portsmouth", "PO5 3AS", "" , 'Restaurant');
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Carluccio's", "Blake House,Gunwarf Quays", "Portsmouth", "PO1 3TH", "", 'Restaurant');
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Zizzi", "Gunwarf Quays", "Portsmouth", "PO1 3TA", "", 'Restaurant');
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Circolo Pizzeria", "78 Osborne Road", "Portsmouth", "PO5 3LU", "", 'Restaurant');
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Bella Italia", "Waterfront, Gunwharf Quays, Unit R10", "Portsmouth", "PO1 3TA", "", 'Restaurant');
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("The Italian Bar & Grill", "30 Great Southsea Street", "Portsmouth", "PO5 3BY", "", 'Restaurant');
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Strada", "R3 Boulevard Building, Gunwarf Quays", "Portsmouth", "PO1 3TW", "", 'Restaurant');
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Azzurro", "Gunwharf Quays, Seafront, Gunwharf Rd", "Portsmouth", "PO1 3TA", "", 'Restaurant');
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Frankie & Benny's", "79 Gunwharf Rd", "Portsmouth", "PO1 3TZ", "", 'Restaurant');
/*42*/insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Koh Thai", "8 King's Road, Southsea", "Portsmouth", "PO5 3AH", "Popular Thai establishment with a great atmosphere", "Restaurant");
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Lin's Thai Cafe", "78 Elm Grove, Southsea", "Portsmouth", "PO5 1LN", "Small but personal authentic Thai restaurant", "Restaurant");
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Thailand Cafe and Takeaway", "186 Albert Road, Southsea", "Portsmouth", "PO6 3DD", "Offering authentic Thai cuisine to eat in or take away", "Restaurant");
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Thai & Laos Kitchen", "176 Fawcett Road, Southsea", "Portsmouth", "PO4 0DP", "A hidden gem serving food with influneces from Thailand and Laos", "Restaurant");
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Rancho Steak House", "61 Osborne Road, Southsea", "Portsmouth", "PO5 3LS", "Classic steak house serving mouthwatering meats", "Restaurant");
/*47*/insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Shorties Restaurant", "8-9 Bellevue Terrace, SOuthsea", "Portsmouth", "PO5 3AT", "Unique steak and burger restraunt often described as a 'hidden gem'", "Restaurant");

/*48*/ insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Anglesea Building", "Anglesea Building, Anglesea Road", "Portsmouth", "PO1 3DJ", "Teaching building for the School of Engineering and School of Law", "University");
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Buckingham Building", "Buckingham Building, Lion Terrace", "Portsmouth", "PO1 3HE", "Teaching building seminar rooms and staff offices", "University");
/*50*/insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Burnaby Building", "Burnaby Building, Burnaby Road", "Portsmouth", "PO1 3QL", "Teaching building in the University North Quarter", "University");
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Burnaby Terrace", "Burnaby Terrace, Burnaby Road", "Portsmouth", "PO1 3AE", "", "University");
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Dennis Sciama Building", "Dennis Sciama Building", "Portsmouth", "PO1 3FX", "Teaching building mainly mad up of small lecture rooms and offices", "University");
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Eldon Buidling", "Eldon Building, Middle Street", "Portsmouth", "PO5 4AY", "Teaching building used mainly for Architecture and desgin students", "University");
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Institute of Marine Science", "Institute of Marine Science, Ferry Road", "Portsmouth", "PO4 9LY", "Reasearch and teaching facility for marine studies", "University");
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("King Henry Building", "King Henry I Building, King Henry Street", "Portsmouth", "PO1 2DY", "Teaching and research building", "University");
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Lion Gate Building", "Lion Gate Building, Lion Terrace", "Portsmouth", "PO1 3HF", "Teaching building made up of seminar rooms staff offices", "University");
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Park Building", "Park Building, King Henry I Street", "Portsmouth", "PO1 2DZ", "Teaching building mainly for langauges and international students", "University");
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Portland Building", "Portland Building, Lion Terrace", "Portsmouth", "PO1 3AH", "Teaching building with PCs, lecture theartres and seminar rooms", "University");
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Richmond Building", "Richmond Building, Portland Street", "Portsmouth", "PO1 3DE", "Teaching building with two lecture theartres, some PCs and seminar rooms. Mainly used by the University Business School", "University");
/*60*/insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Spinnaker Building", "2 Cambridge Road", "Portsmouth", "PO1 2EF", "Teaching building mainly used by the University Sports Science Department ", "University");
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("St Andrews Court", "St Andrews Court, St Michael's Road", "Portsmouth", "PO1 2PR", "Teaching building with multiple computer and seminar classrooms", "University");
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("St George's Building", "141 High Street", "Portsmouth", "PO1 2HY", "Teaching and research building", "University");
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("St Michael's Building", "St Michael's Building, King Henry I Street", "Portsmouth", "PO1 2DT", "Teaching building with research and seminar facilities", "University");
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("St Paul's Sports Centre", "St Paul's Gym, St Paul's Road", "Portsmouth", "PO5 4AQ", "Sports facility containing gym, sports hall and fitness rooms", "University");
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("University of Portsmouth Students Union", "UPSU, Cambridge Road", "Portsmouth", "PO1 2EF", "Union buidling for students made up of a shop, bar, multi-use space and staff offices", "University");
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("University Library", "University Library, Cambridge Road", "Portsmouth", "PO1 2ST", "Multi-level library with slefstudy, group study and small seminar space", "University");
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("William Beatty Building", "22 Hampshire Terrace", "Portsmouth", "PO1 2QB", "Dental Academy", "University");
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Langstone student Village", "Langstone Student Village, Furze Lane", "Portsmouth", "PO4 8Lw", "University's Eastern campus made up of sports fields and student accomodation", "University");
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Bateson Hall", "Bateson Hall, The Mary Rose Street", "Portsmouth", "PO1 2BL", "Students halls of residence", "University");
/*70*/insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Catherine House", "Catherine House, Stanhope Road", "Portsmouth", "PO1 1DZ", "Students halls of residence", "University");
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Greetham Street Halls", "Greetham Street Halls, Greetham street", "Portsmouth", "PO5 4FB", "Students halls of residence", "University");
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Harry Law Halls", "Harry Law Halls, Isambard Brunel Road", "Portsmouth", "PO1 2SP", "Students halls of residence", "University");
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("James Watson Halls", "28 Guildhall Walk", "Portsmouth", "PO1 2DD", "Students halls of residence", "University");
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Margaret Rule Halls", "Margaret Rule Halls, Isambard Brunel Road", "Portsmouth", "PO1 2DS", "Students halls of residence", "University");
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Rees Halls", "Rees Halls, Southsea Terrace", "Portsmouth", "PO5 3AP", "Students halls of residence", "University");
/*76*/insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Trafalgar Halls", "Trafalgar Halls, Middle Street", "Portsmouth", "PO5 4AY", "Students halls of residence", "University");

/*77*/insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("The Astoria", "37-39 Guildhall Walk", "Portsmouth", "PO1 2RY", "Popular and lively nightclub with themed events including student nights, 80s nights and dance nights", "NightClub");
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Popworld", "1 King Henry I Street", "Portsmouth", "PO1 2PT", "Fun and friendly club dedicated to sing along and pop songs", "NightClub");
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Pryzm", "Pryzm Nightclub, Stanhope Road", "Portsmouth", "PO1 1DU", "Portsmouth's newest nightclub, one of a chain of clubs across the country", "NightClub");
/*80*/insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Zanzi", "4-8 Guildhall Walk", "Portsmouth", "PO1 2DD", "Small but lively club with themed nights and a jungle design", "NightClub");

/*81*/insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Honest Politician", "47 Elm Grove", "Portsmouth", "PO5 1JF", "A casual bar which offers cocktails, pool and darts", 'Bar');
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Lyberry", "29-33 Guildhall Walk", "Portsmouth", "PO1 2RY", "Bar / Nightclub connected to Astoria", 'Bar');
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Barley Mow", "29 Castle Road", "Portsmouth", "PO5 3DE", "Cosy and classic English pub", "Bar");
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Leopold Tavern", "154 Albert Road", "Portsmouth", "PO4 0Jt", "Recently refurbished modern pub styled in a traditional fashion", "Bar");
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Little Johnny Russells", "14 Albert Road", "Portsmouth", "PO6 3DD", "Recently refurbished and revamped bar with a great atmosphere", "Bar");
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("The Deco", "128 Elm Grove", "Portsmouth", "PO5 1LR", "Known for live music and event nights", "Bar");
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Slug and Lettuce Southsea", "80-82 Palmerston Road", "Portsmouth", "PO5 3PT", "One of the nationwide chain know afordable but classy drinks, especially cocktails", "Bar");
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("The Old Oyster House", "291 Locksway Road", "Portsmouth", "PO4 8LH", "Traditional pub on Portsmouth's East coast", "Bar");
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("The Waterhole Bar", "Unit 3 Cambridge Road", "Portsmouth", "PO1 2EF", "Student bar inside the student's union known for cheap drinks and events", "Bar");
/*90*/insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("The Isambard Kingdom Brunel- Wetherspoons", "2 Guildhall Walk", "Portsmouth", "PO1 2DD", "This Wetherspoons continues the chain's theme of cheap food and drink", "Bar");
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Yates", "13-19 Guildhall Walk", "Portsmouth", "PO1 2RY", "Cheap bar for food and drink, often with a great atmosphere during sporting events", "Bar");
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("The Lord Palmerston- Wetherpsoons", "84-90 Palmerston Road", "Portsmouth", "PO5 3PT", "Known for cheap drinks and food, with themed nights for food deals", "Bar");
insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("The One Eyed Dog", "177-185 Elm Grove", "Portsmouth", "PO5 1LU", "Known for lively entertainemnt and themed events", "Bar");
/*94*/insert into Establishment (Name, Address, Town, Postcode, Description, Category) values ("Brewhouse and Kitchen", "26 Guildhall Walk", "Portsmouth", "PO1 2DD", "More expensive than most pubs, but great traditional Ales and food options", "Bar");

/*Inserting into Contact*/
insert into Contact_Info values (1, "023 9229 3797", "Gunwharf@iguanas.co.uk","https://www.iguanas.co.uk/restaurants/portsmouth", "https://www.facebook.com/LasIguanasGunwharfQuays/");
insert into Contact_Info values (2, "023 9287 6272", NULL,"restaurant27.com", "https://www.facebook.com/Restaurant-27-169409896445091/");
insert into Contact_Info values (3, "023 9275 3914", NULL,"pieandvinyl.co.uk", "https://www.facebook.com/pieandvinyl/");
insert into Contact_Info values (4, "023 9200 8555", "info@thekitchensouthsea.co.uk"," thekitchensouthsea.co.uk", "https://www.facebook.com/thekitchensouthsea/");
insert into Contact_Info values (5, "023 9282 3569", "book@samphire.co","http://www.samphire.co/", "https://en-gb.facebook.com/samphiresouthsea/");
insert into Contact_Info values (6, "023 9281 6754", NULL,"bistromontparnasse.com", "https://www.facebook.com/bistromontparnasse/");
insert into Contact_Info values (7, "023 9286 5000", "info@BeckettsSouthsea.co.uk","beckettssouthsea.co.uk", "https://www.facebook.com/beckettssouthsea/");
insert into Contact_Info values (8, "023 9217 8878", NULL,"http://thewavemaiden.co.uk/", "https://www.facebook.com/thewavemaidensouthsea/");
insert into Contact_Info values (9, "023 9289 1320", "portsmouth@brasserieblanc.com","brasserieblanc.com", "https://www.facebook.com/BBPortsmouth/");
insert into Contact_Info values (10, "023 9281 1585", "info@abarbistro.co.uk"," abarbistro.co.uk", "https://www.facebook.com/abarbistro/");
insert into Contact_Info values (11, "023 9281 8270", "book@thechambers.co.uk","thechambers.co.uk", "https://www.facebook.com/thechambersdining");
insert into Contact_Info values (12, "023 9282 0116", NULL,"haldi-portsmouth.co.uk", "https://www.facebook.com/Haldi-restaurant-296105177472561/");
insert into Contact_Info values (13, "023 9282 8900", "mail@spicemerchants-portsmouth.couk","spicemerchants-portsmouth.co.uk", "https://www.facebook.com/spicemerchantsportsmouth/");
insert into Contact_Info values (14, "023 9286 2518", NULL,"purple-mango.co.uk", "https://www.facebook.com/purplemangosouthsea/");
insert into Contact_Info values (15, "023 9281 5824", NULL,"tjmahal.co.uk", "https://www.facebook.com/TandJMahalRestaurant");
insert into Contact_Info values (16, "023 9266 9636", NULL,"massalaroom.co.uk", "https://www.facebook.com/themassalaroom/");
insert into Contact_Info values (17, "023 9281 1966", "enquiries@thegandhirestaurant.co.uk","http://gandhirestaurant.co.uk/", "https://www.facebook.com/The-Gandhi-Restaurant-134025996647558/");
insert into Contact_Info values (18, "023 9282 2567", NULL,"spicerouteindian.co.uk", "https://www.facebook.com/spicerouteindiancuisine/");
insert into Contact_Info values (19, "023 9273 0300", "hello@kadirsindian.com","http://www.kadirsindian.com/", "https://www.facebook.com/kadirsindian");
insert into Contact_Info values (20, "023 9281 1114", NULL,"http://www.kassia.co.uk/southsea/", "https://www.facebook.com/kassiasouthsea/");
insert into Contact_Info values (21, "023 9229 1813", "info@theakash.com","theakash.co.uk", "https://www.facebook.com/TheAkashRest/");
insert into Contact_Info values (22, "023 9285 1155", NULL,"http://www.tintin.org.uk/", "https://www.facebook.com/pages/Tin-Tin/154343644590739");
insert into Contact_Info values (23, "023 9282 6880", NULL,"noblehousesouthsea.com", "https://www.facebook.com/NobleHouseRestaurant/?fref=ts");
insert into Contact_Info values (24, "023 9217 6766", NULL,"http://realchina.123eat.co.uk/", "https://www.facebook.com/pages/Real-China/455306344653742");
insert into Contact_Info values (25, "023 9273 2999", NULL,NULL, "https://en-gb.facebook.com/pages/Wok-Chips/118330731554513");
insert into Contact_Info values (26, "023 9275 3104", NULL,"http://www.thebigeat.com/uk/takeaway/kam_too", "https://en-gb.facebook.com/pages/Kam-Too/103228303074019");
insert into Contact_Info values (27, "023 9242 0124", NULL,NULL, "https://www.facebook.com/Golden-Bowl-173205556193465/");
insert into Contact_Info values (28, "023 9273 3353", NULL,"https://restaurantguru.com/Mayfair-Chinese-Restaurant-Portsmouth", "https://www.facebook.com/pages/Mayfair-Chinese-Restaurant/140537982657168");
insert into Contact_Info values (29, "023 9282 1888", NULL,"https://www.just-eat.co.uk/restaurants-yan-woo-restaurant-north-end/menu", "https://en-gb.facebook.com/Yan-Woo-Portsmouth-134546716598655/");
insert into Contact_Info values (30, "023 9275 1751", NULL,"https://www.just-eat.co.uk/restaurants-maryrosedragon-po1/menu", "https://www.facebook.com/pages/Mary-Rose-and-Dragon-Restaurant/304149739597072");
insert into Contact_Info values (31, "023 9273 8822", NULL,"http://www.spicyhouse.co.uk/", "https://en-gb.facebook.com/SpicyHouseChineseTA/");
insert into Contact_Info values (32, "023 9281 1139", "info@sopranos-southsea.com","sopranos-southsea.com", "https://en-gb.facebook.com/sopranossouthsea/");
insert into Contact_Info values (33, "023 9282 2200", NULL,"donclaudio.co.uk", "https://www.facebook.com/Don.ClaudioItalianRestaurant");
insert into Contact_Info values (34, "023 9287 6372", "portsmouth@carluccios.com","https://carluccios.com/restaurants/portsmouth", "https://www.facebook.com/carluccios");
insert into Contact_Info values (35, "023 9217 5111", NULL,"https://www.zizzi.co.uk/italian/restaurants/portsmouth/gunwharf-quays", "https://www.facebook.com/wearezizzi/");
insert into Contact_Info values (36, "023 9234 9079", NULL,"http://circolo.co.uk/", "https://en-gb.facebook.com/Circolo-Pizzeria-1394994880717813/");
insert into Contact_Info values (37, "023 9286 4444", "portsmouthgwquays@bellaitalia.co.uk","https://www.bellaitalia.co.uk/italian-restaurant/portsmouth/gunwharf-quays", "https://www.facebook.com/bellaitalia.co.uk/");
insert into Contact_Info values (38, "023 9275 3058", NULL,"http://www.theibar.co.uk/menu/", NULL);
insert into Contact_Info values (39, "023 9281 7278", NULL,"http://www.strada.co.uk/italian-restaurant/portsmouth-gunwharf-quays", "https://www.facebook.com/strada.co.uk");
insert into Contact_Info values (40, "023 9283 2111", NULL,"http://azzurro-restaurant.co.uk/location/portsmouth/", "https://en-gb.facebook.com/AzzurroPortsmouth/");
insert into Contact_Info values (41, "023 9273 2151", NULL,"https://gunwharf-quays.com/food-and-drink/frankie-bennys", "https://www.facebook.com/FrankieBennys");
insert into Contact_Info values (42, "02392 824825", NULL,"https://www.koh-thai.co.uk/restaurant/southsea/", "https://www.facebook.com/KohSouthsea");
insert into Contact_Info values (43, "023 9229 1115", "linsthaicafe@gmail.com","http://www.linsthaicafe.co.uk/", "https://www.facebook.com/pages/Lins-Thai-Cafe/108968619163067");
insert into Contact_Info values (44, "023 9242 1242", NULL,"https://southseafoodsocial.co.uk/2014/03/15/thai-cafe-takeaway/", "https://www.just-eat.co.uk/restaurants-thailand-cafe-po4");
insert into Contact_Info values (45, "07519 731190", NULL, "http://tasteofportsmouth.co.uk/restaurant/thai-laos-kitchen/", "https://www.facebook.com/Thai-Laos-Kitchen-1524812847783615/");
insert into Contact_Info values (46, "023 9273 7235", "ranchoportsmouth@gmail.com","http://www.ranchosteakhouseportsmouth.com/menu/", "https://en-gb.facebook.com/ranchosteakhouseltd/");
insert into Contact_Info values (47, "023 9283 1941", NULL,"shortiesrestaurant.com", "https://en-gb.facebook.com/shortiesrestaurant/");

/*Inserting into Time*/
insert into Work_Time values (1, '10:00:00', '23:00:00', '10:00:00', '23:00:00', '10:00:00', '23:00:00', '10:00:00', '23:00:00', '10:00:00', '00:00:00', '10:00:00', '00:00:00', '10:00:00', '22:30:00');

/*Inserting into Resturant*/
insert into Restaurant (Est_Id, Cuisine, Type) values (1, "Latin Food Chain", "Sit Down, Family");
insert into Restaurant (Est_Id, Cuisine, Type) values (2, "French", "Sit Down, Expensive");
insert into Restaurant (Est_Id, Cuisine, Type) values (3, "British", "Sit Down, Casual");
insert into Restaurant (Est_Id, Cuisine, Type) values (4, "Locally Sourced", "Sit Down, Expensive");
insert into Restaurant (Est_Id, Cuisine, Type) values (5, "Locally Sourced", "Sit Down, Adult");
insert into Restaurant (Est_Id, Cuisine, Type) values (6, "Locally Sourced", "Sit Down, Expensive");
insert into Restaurant (Est_Id, Cuisine, Type) values (7, "Bistro", "Sit Down, Casual");
insert into Restaurant (Est_Id, Cuisine, Type) values (8, "Pub", "Pub, Casual");
insert into Restaurant (Est_Id, Cuisine, Type) values (9, "French", "Upper Class, Mid Range");Cusine
insert into Restaurant (Est_Id, Cuisine, Type) values (10, "International", "Casual");
insert into Restaurant (Est_Id, Cuisine, Type) values (11, "Sophisticated lounge", "High Class, Expensive");
insert into Restaurant (Est_Id, Cuisine, Type) values (12, "Indian", "Sit Down, Casual");
insert into Restaurant (Est_Id, Cuisine, Type) values (13, "Indian", "Sit Down, Casual");
insert into Restaurant (Est_Id, Cuisine, Type) values (14, "Indian", "Sit Down, Casual");
insert into Restaurant (Est_Id, Cuisine, Type) values (15, "Indian", "Sit Down, Casual");
insert into Restaurant (Est_Id, Cuisine, Type) values (16, "Indian", "Sit Down, Casual");
insert into Restaurant (Est_Id, Cuisine, Type) values (17, "Indian", "Sit Down, Casual");
insert into Restaurant (Est_Id, Cuisine, Type) values (18, "Indian", "Sit Down, Casual");
insert into Restaurant (Est_Id, Cuisine, Type) values (19, "Indian", "Sit Down, Casual");
insert into Restaurant (Est_Id, Cuisine, Type) values (20, "Indian", "Sit Down, Casual");
insert into Restaurant (Est_Id, Cuisine, Type) values (21, "Indian", "Sit Down, Casual");
insert into Restaurant (Est_Id, Cuisine, Type) values (22, "Chinese", "Sit Down, Cheap");
insert into Restaurant (Est_Id, Cuisine, Type) values (23, "Chinese", "Sit Down, Casual");
insert into Restaurant (Est_Id, Cuisine, Type) values (24, "Chinese", "Sit Down, Takeaway");
insert into Restaurant (Est_Id, Cuisine, Type) values (25, "Chinese", "Sit Down, Takeaway");
insert into Restaurant (Est_Id, Cuisine, Type) values (26, "Chinese", "Sit Down, Casual");
insert into Restaurant (Est_Id, Cuisine, Type) values (27, "Chinese", "Sit Down, Cheap");
insert into Restaurant (Est_Id, Cuisine, Type) values (28, "Chinese", "Sit Down, Takeaway");
insert into Restaurant (Est_Id, Cuisine, Type) values (29, "Chinese", "Sit Down, Casual");
insert into Restaurant (Est_Id, Cuisine, Type) values (30, "Chinese", "Sit Down, Takeaway");
insert into Restaurant (Est_Id, Cuisine, Type) values (31, "Chinese", "Sit Down, Cheap");
insert into Restaurant (Est_Id, Cuisine, Type) values (32, "Italian", "Sit Down, Casual");
insert into Restaurant (Est_Id, Cuisine, Type) values (33, "Italian", "Sit Down, Personal");
insert into Restaurant (Est_Id, Cuisine, Type) values (34, "Italian", "Sit Down, Chain");
insert into Restaurant (Est_Id, Cuisine, Type) values (35, "Italian", "Sit Down, Chain");
insert into Restaurant (Est_Id, Cuisine, Type) values (36, "Italian", "Sit Down, Casual");
insert into Restaurant (Est_Id, Cuisine, Type) values (37, "Italian", "Sit Down, Chain");
insert into Restaurant (Est_Id, Cuisine, Type) values (38, "Italian", "Sit Down, Casual");
insert into Restaurant (Est_Id, Cuisine, Type) values (39, "Italian", "Sit Down, Chain");
insert into Restaurant (Est_Id, Cuisine, Type) values (40, "Italian", "Sit Down, Casual");
insert into Restaurant (Est_Id, Cuisine, Type) values (41, "Italian and American", "Sit Down, Chain");
insert into Restaurant (Est_Id, Cuisine, Type) values (42, "Thai", "Sit Down, Takeaway");
insert into Restaurant (Est_Id, Cuisine, Type) values (43, "Thai", "Sit Down, Takeaway");
insert into Restaurant (Est_Id, Cuisine, Type) values (44, "Thai", "Sit Down, Takeaway");
insert into Restaurant (Est_Id, Cuisine, Type) values (45, "Thai", "Sit Down, Cosy");
insert into Restaurant (Est_Id, Cuisine, Type) values (46, "Steak", "Sit Down, Good for Groups");
insert into Restaurant (Est_Id, Cuisine, Type) values (47, "Steak", "Sit Down, Casual");

/*Inserting into University*/
insert into University (Est_Id, Canteen, Free_PCs) values (48, True, True);
insert into University (Est_Id, Canteen, Free_PCs) values (49, False, False);
insert into University (Est_Id, Canteen, Free_PCs) values (50, False, False);
insert into University (Est_Id, Canteen, Free_PCs) values (51, False, Flase);
insert into University (Est_Id, Canteen, Free_PCs) values (52, True, False);
insert into University (Est_Id, Canteen, Free_PCs) values (53, True, True);
insert into University (Est_Id, Canteen, Free_PCs) values (54, False, False);
insert into University (Est_Id, Canteen, Free_PCs) values (55, False, False);
insert into University (Est_Id, Canteen, Free_PCs) values (56, False, True);
insert into University (Est_Id, Canteen, Free_PCs) values (57, True, True);
insert into University (Est_Id, Canteen, Free_PCs) values (58, True, True);
insert into University (Est_Id, Canteen, Free_PCs) values (59, False, True);
insert into University (Est_Id, Canteen, Free_PCs) values (60, False, False);
insert into University (Est_Id, Canteen, Free_PCs) values (61, True, False);
insert into University (Est_Id, Canteen, Free_PCs) values (62, True, False);
insert into University (Est_Id, Canteen, Free_PCs) values (63, False, False);
insert into University (Est_Id, Canteen, Free_PCs) values (64, False, Flase);
insert into University (Est_Id, Canteen, Free_PCs) values (65, True, False);
insert into University (Est_Id, Canteen, Free_PCs) values (66, True, True);
insert into University (Est_Id, Canteen, Free_PCs) values (67, False, False);
insert into University (Est_Id, Canteen, Free_PCs) values (68, True, False);
insert into University (Est_Id, Canteen, Free_PCs) values (69, False, False);
insert into University (Est_Id, Canteen, Free_PCs) values (70, False, False);
insert into University (Est_Id, Canteen, Free_PCs) values (71, False, False);
insert into University (Est_Id, Canteen, Free_PCs) values (72, False, False);
insert into University (Est_Id, Canteen, Free_PCs) values (73, False, False);
insert into University (Est_Id, Canteen, Free_PCs) values (74, False, False);
insert into University (Est_Id, Canteen, Free_PCs) values (75, False, False);
insert into University (Est_Id, Canteen, Free_PCs) values (76, False, False);

/*Inserting into NightClub*/
insert into NightClub (Est_Id, CostOfEntry) values (3, 6.00);
insert into NightClub (Est_Id, CostOfEntry) values ((select Establishment.Est_Id from Establishment where Establishment.Name = 'Lyberry'), 6.00);

/*Inserting into Bar*/
insert into Bar (Est_Id, Atmosphere, Type) values (4, "Relaxed | Traditonal", "Student Bar");
insert into Bar (Est_Id, Atmosphere, Type) values (5, "Lively | Loud Music", "Nightclub Bar");
